### ISSUE TITLE
A new way to Increase the number of V3 instances to more than 8

### ISSUE THREAD

**Issue by ninjab67** [asn-d6/onionbalance#34]
I recently read this on an underground forum in which an onion site operator shared a way of increasing the number of v3 instances to more than 8 (which is currently the limit imposed by onionbalance). I will share his post word by word exactly. My question is Is this a safe way to increase the number of instances? If this is not safe way to do then when can we expect an official update in which you guys increase the number instances to more than 8.

 
> i changed the parameters in the following files:
> 
> ./onionbalance/build/lib/onionbalance/hs_v3/params.py
> ./onionbalance/onionbalance/hs_v3/params.py
> 
> In the following ones:
> 
> N_INTROS_PER_INSTANCE = 1
> HSDIR_N_REPLICAS = 2
> HSDIR_SPREAD_STORE = 2
> 
> This will reduce the file descriptor size and allow you to publish more than 8 instances in your onionbalancer.
> But now you will say:
> 
> - What the fuck dude, i did it and it doesnt work! -
> 
> Yes, true two things that can happens are:
> 
> 1. Onion site not found (even if you see that descriptors has been published)
> 2. Error from the Onionbalancer logs with "Descriptor is too big to be published"
> 
> Well, in such case the changes on the params.py, has not be applied as expected.
> What you should do now?
> 
> Well i see that there are two main factors that have to be changed\removed in order to have a good tuneup of your configuration.
> 
> 1. Vanguard: Vanguard is not a tool that is often updated and may create a lot of problems in the process to publish the descriptors, even if i don't have discovered the reason or the way. I fixed it using the params (/etc/tor/vanguards.conf)
> 
> 
> If True, we write (or update/rotate) layer2 and layer3 vanguards in torrc,
> then exit. This option disables the bandguards and rendguard defenses.
> one_shot_vanguards = True
> 
> Setting it to true, you'll lose some defense, but that defense in our case are not required and the one_shot can easily allow the vanguards and our tor to quicky rotate the layers.
> If you want, you can remove totally vanguards since about now create more than one problem in the OnionBalancer.
> 
> 2. Onionbalancer rebuild.
> 
> Looks stupid, right? but yes.
> You must rebuild with following commands once your setup is done:
> 
> python3 setup.py build
> python3 setup.py install
> 
> This will make effective the changes on the configs.

**Comment by asn-d6** [comment]
That might work to increase the number of instances but it's also totally wrong for a bunch of reasons. I'd suggest to be very careful of the things that people say in underground forums. The right way to do this is https://github.com/asn-d6/onionbalance/issues/11 and I hope that someone submits a patch for it. It shouldn't be that hard.
